/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstallationRouteImport } from './routes/installation'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as ThemingRouteImport } from './routes/theming'
import { Route as ComponentsSlugRouteImport } from './routes/components.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationRoute = InstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemingRoute = ThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: '/components/$slug',
  path: '/components/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/installation': typeof InstallationRoute
  '/registry': typeof RegistryRoute
  '/theming': typeof ThemingRoute
  '/components/$slug': typeof ComponentsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/installation': typeof InstallationRoute
  '/registry': typeof RegistryRoute
  '/theming': typeof ThemingRoute
  '/components/$slug': typeof ComponentsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/installation': typeof InstallationRoute
  '/registry': typeof RegistryRoute
  '/theming': typeof ThemingRoute
  '/components/$slug': typeof ComponentsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/installation' | '/registry' | '/theming' | '/components/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/installation' | '/registry' | '/theming' | '/components/$slug'
  id:
    | '__root__'
    | '/'
    | '/installation'
    | '/registry'
    | '/theming'
    | '/components/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstallationRoute: typeof InstallationRoute
  RegistryRoute: typeof RegistryRoute
  ThemingRoute: typeof ThemingRoute
  ComponentsSlugRoute: typeof ComponentsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation': {
      id: '/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof InstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theming': {
      id: '/theming'
      path: '/theming'
      fullPath: '/theming'
      preLoaderRoute: typeof ThemingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/components/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstallationRoute: InstallationRoute,
  RegistryRoute: RegistryRoute,
  ThemingRoute: ThemingRoute,
  ComponentsSlugRoute: ComponentsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
